export const GET_PIZZAS_REQUEST = "GET_PIZZAS_REQUEST";
export const GET_PIZZAS_SUCCESS = "GET_PIZZAS_SUCCESS";
export const GET_PIZZAS_FAIL = "GET_PIZZAS_FAIL";
export const GET_PIZZA_DETAILS_REQUEST = "GET_PIZZA_DETAILS_REQUEST";
export const GET_PIZZA_DETAILS_SUCCESS = "GET_PIZZA_DETAILS_SUCCESS";
export const GET_PIZZA_DETAILS_FAIL = "GET_PIZZA_DETAILS_FAIL";
export const GET_PIZZA_DETAILS_RESET = "GET_PIZZA_DETAILS_RESET";
